spring.application.name=erp

# ===============================
# ===============================
# BANCO DE DADOS (MySQL Local)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ===============================
# SEGURANÇA E CORS (Ligação com o Angular)
# ===============================
app.security.username=${ERP_USER}
app.security.password=${ERP_SECURITY_PASSWORD}
app.cors.allowed-origin=${CORS_ORIGIN:http://localhost:4200}

# ===============================
# UPLOADS (Imagens dos Produtos)
# ===============================
app.upload.directory=${UPLOAD_DIR:uploads}
app.upload.public-url=${UPLOAD_URL:http://localhost:8080/uploads}

# ===============================
# MERCADO PAGO
# ===============================
app.mercadopago.token=${MP_TOKEN}

# ===============================
# E-MAIL (Envio de Recibos em PDF)
# ===============================
app.mail.enabled=${MAIL_ENABLED}
app.mail.from=${MAIL_FROM}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

supabase.s3.endpoint=https://ejkagkpcdpgtpmozevff.storage.supabase.co/storage/v1/s3
supabase.s3.region=sa-east-1
supabase.s3.access-key=${S3_ACCESS_KEY}
supabase.s3.secret-key=${S3_SECRET_KEY}
supabase.s3.bucket=produtos
supabase.s3.public-url=https://ejkagkpcdpgtpmozevff.supabase.co/storage/v1/object/public/